// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/es/get/": {
            "get": {
                "description": "根据id获取对象，可以是author，work，institution,venue,concept",
                "tags": [
                    "esSearch"
                ],
                "summary": "txc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":201,\"msg\":\"id type error\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/search/advanced": {
            "post": {
                "description": "高级搜索，搜索条件通过body传入，未完成",
                "responses": {}
            }
        },
        "/es/search/base2": {
            "post": {
                "description": "基本搜索2，Cond里面填筛选条件，key仅包含[\"type\", \"author\", \"institution\", \"publisher\", \"venue\", \"publication_year\"]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "esSearch"
                ],
                "summary": "txc",
                "parameters": [
                    {
                        "description": "搜索条件",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.BaseSearchQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":201,\"err\":\"es search err\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/search/doi": {
            "post": {
                "description": "使用doi查找work，未测试，请勿使用",
                "tags": [
                    "esSearch"
                ],
                "summary": "txc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "doi",
                        "name": "doi",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/es/test_es": {
            "post": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "queryWord",
                        "name": "queryWord",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "ccf",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":202,\"success\":false,\"msg\":\"password doesn't match\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "填入用户名和密码注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "ccf",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.RegisterQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":201,\"msg\":\"username exists\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/userinfo": {
            "post": {
                "description": "查看用户个人信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "ccf",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200,\"success\":false,\"msg\":\"userID not exist\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/usermod": {
            "post": {
                "description": "编辑用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "ccf",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "个性签名",
                        "name": "user_info",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "电话号码",
                        "name": "phone_number",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200,\"success\":false,\"msg\":err.Error()}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.BaseSearchQ": {
            "type": "object",
            "properties": {
                "conds": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "kind": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "queryWord": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "sort": {
                    "type": "integer"
                }
            }
        },
        "response.RegisterQ": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
