info:
  contact: {}
paths:
  /es/test_es:
    post:
      parameters:
      - description: queryWord
        in: formData
        name: queryWord
        required: true
        type: string
      responses: {}
swagger: "2.0"
