definitions:
  response.AdvancedSearchQ:
    properties:
      asc:
        type: boolean
      conds:
        additionalProperties:
          type: string
        type: object
      page:
        type: integer
      query:
        items:
          additionalProperties:
            type: string
          type: object
        type: array
      size:
        type: integer
      sort:
        type: integer
    type: object
  response.AuthorRelationNet:
    properties:
      edge_set:
        items:
          additionalProperties: true
          type: object
        type: array
      vertex_set:
        items:
          additionalProperties: true
          type: object
        type: array
    type: object
  response.BaseSearchQ:
    properties:
      asc:
        type: boolean
      conds:
        additionalProperties:
          type: string
        type: object
      kind:
        type: string
      page:
        type: integer
      queryWord:
        type: string
      size:
        type: integer
      sort:
        type: integer
    type: object
  response.LoginQ:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  response.ModifyQ:
    properties:
      email:
        description: 邮箱
        type: string
      fields:
        description: 研究领域
        type: string
      interest_tag:
        description: 兴趣词
        type: string
      name:
        description: 真实姓名
        type: string
      phone:
        description: 电话号码
        type: string
      user_info:
        description: 个性签名
        type: string
    type: object
  response.RegisterQ:
    properties:
      password:
        minLength: 6
        type: string
      username:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /es/get/:
    get:
      description: 根据id获取对象，可以是author，work，institution,venue,concept
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"status":200,"res":{obeject}}'
          schema:
            type: string
        "201":
          description: '{"status":201,"msg":"es get err"}'
          schema:
            type: string
        "400":
          description: '{"status":400,"msg":"id type error"}'
          schema:
            type: string
      summary: txc
      tags:
      - esSearch
  /es/getAuthorRelationNet:
    get:
      description: |
        根据author的id获取专家关系网络, 目前会返回Top N的关系网，N=10，后续可以讨论修改N的大小或者传参给我

        目前接口时延约为1s, 后续考虑把计算出来的结果存入数据库，二次查询时延降低
      parameters:
      - description: author_id
        enum:
        - A2764814280
        - A2900471938
        - A2227665069
        in: query
        name: author_id
        required: true
        type: string
      responses:
        "200":
          description: '{"data":{ "Vertex_set":[], "Edge_set":[]}}'
          schema:
            $ref: '#/definitions/response.AuthorRelationNet'
        "201":
          description: '{"msg":"Get Author Relation Net Error"}'
          schema:
            type: string
      summary: hr
      tags:
      - esSearch
  /es/search/advanced:
    post:
      consumes:
      - application/json
      description: |-
        高级搜索，query是一个map列表， 每个map包含"content" "field" "logic"
        logic 仅包含["and", "or", "not"]
        field 仅包含["title", "abstract", "venue", "publisher", "author", "institution", "concept"]
        对于年份的筛选，在query里面 field是"publication_date" logic默认为and， 该map下有"begin" "end"分别是开始和结束
        sort=0为默认排序（降序） =1为按引用数降序 =2按发表日期由近到远
        asc=0为降序 =1为升序
        { "asc": false,"conds": {"venue":"International Journal for Research in Applied Science and Engineering Technology","author": "Zenith Nandy"},"page": 1,"query": [{"field": "title","content": "python","logic": "and"},{"field": "publication_date","begin": "2021-12-01","end":"2022-06-01","logic": "and"}],"size": 8,"sort": 0}
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.AdvancedSearchQ'
      produces:
      - application/json
      responses: {}
      summary: txc
      tags:
      - esSearch
  /es/search/base:
    post:
      consumes:
      - application/json
      description: 基本搜索，Cond里面填筛选条件，key仅包含["type", "author", "institution", "publisher",
        "venue", "publication_year"]
      parameters:
      - description: 搜索条件
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.BaseSearchQ'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"res":{obeject}}'
          schema:
            type: string
        "201":
          description: '{"status":201,"err":"es search err"}'
          schema:
            type: string
      summary: txc
      tags:
      - esSearch
  /es/search/doi:
    post:
      description: 使用doi查找work，未测试，请勿使用
      parameters:
      - description: doi
        in: query
        name: doi
        required: true
        type: string
      responses: {}
      summary: txc
      tags:
      - esSearch
  /login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.LoginQ'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"success":true,"msg":"login success","token":
            666}'
          schema:
            type: string
        "400":
          description: '{"status":400,"success":false,"msg":"username doesn''t exist"}'
          schema:
            type: string
        "401":
          description: '{"status":401,"success":false,"msg":"password doesn''t match"}'
          schema:
            type: string
      summary: ccf
      tags:
      - 用户
  /register:
    post:
      consumes:
      - application/json
      description: 填入用户名和密码注册
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.RegisterQ'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"msg":"register success"}'
          schema:
            type: string
        "400":
          description: '{"status":400,"msg":"username exists"}'
          schema:
            type: string
      summary: ccf
      tags:
      - 用户
  /user/headshot:
    post:
      consumes:
      - application/json
      description: 上传用户头像
      parameters:
      - description: 新头像
        in: formData
        name: Headshot
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"msg":"修改成功","data":{object}}'
          schema:
            type: string
        "400":
          description: '{"status":400,"msg":"用户ID不存在"}'
          schema:
            type: string
        "401":
          description: '{"status":401,"msg":"头像文件上传失败"}'
          schema:
            type: string
        "402":
          description: '{"status":402,"msg":"文件保存失败"}'
          schema:
            type: string
        "403":
          description: '{"status":403,"msg":"保存文件路径到数据库中失败"}'
          schema:
            type: string
      summary: ccf
      tags:
      - 用户
  /user/info:
    get:
      consumes:
      - application/json
      description: 查看用户个人信息
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"msg":"get info of user","data":{object}}'
          schema:
            type: string
        "400":
          description: '{"status":400,"msg":"userID not exist"}'
          schema:
            type: string
      summary: ccf
      tags:
      - 用户
  /user/mod:
    post:
      consumes:
      - application/json
      description: 编辑用户信息
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.ModifyQ'
      - description: 个性签名
        in: query
        name: user_info
        required: true
        type: string
      - description: 电话号码
        in: query
        name: phone_number
        required: true
        type: string
      - description: Email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"msg":"修改成功","data":{object}}'
          schema:
            type: string
        "400":
          description: '{"status":400,"msg":"用户ID不存在"}'
          schema:
            type: string
        "401":
          description: '{"status":401,"msg":err.Error()}'
          schema:
            type: string
      summary: ccf
      tags:
      - 用户
  /user/pwd:
    post:
      consumes:
      - application/json
      description: 编辑用户信息
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      - description: 旧密码
        in: formData
        name: Password_Old
        required: true
        type: string
      - description: 新密码
        in: formData
        name: Password_New
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"msg":"修改成功","data":{object}}'
          schema:
            type: string
        "400":
          description: '{"status":400,"msg":"用户ID不存在"}'
          schema:
            type: string
        "401":
          description: '{"status":401,"msg":"原密码输入错误"}'
          schema:
            type: string
        "402":
          description: '{"status":402,"msg":err1.Error()}'
          schema:
            type: string
      summary: ccf
      tags:
      - 用户
swagger: "2.0"
