definitions:
  response.BaseSearchQ:
    properties:
      conds:
        additionalProperties:
          type: string
        type: object
      kind:
        type: string
      page:
        type: integer
      queryWord:
        type: string
      size:
        type: integer
      sort:
        type: integer
    type: object
  response.RegisterQ:
    properties:
      password:
        minLength: 6
        type: string
      username:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /es/get/:
    get:
      description: 根据id获取对象，可以是author，work，institution,venue,concept
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"status":201,"msg":"id type error"}'
          schema:
            type: string
      summary: txc
      tags:
      - esSearch
  /es/search/advanced:
    post:
      description: 高级搜索，搜索条件通过body传入，未完成
      responses: {}
  /es/search/base2:
    post:
      consumes:
      - application/json
      description: 基本搜索2，Cond里面填筛选条件，key仅包含["type", "author", "institution", "publisher",
        "venue", "publication_year"]
      parameters:
      - description: 搜索条件
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.BaseSearchQ'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":201,"err":"es search err"}'
          schema:
            type: string
      summary: txc
      tags:
      - esSearch
  /es/search/doi:
    post:
      description: 使用doi查找work，未测试，请勿使用
      parameters:
      - description: doi
        in: query
        name: doi
        required: true
        type: string
      responses: {}
      summary: txc
      tags:
      - esSearch
  /es/test_es:
    post:
      parameters:
      - description: queryWord
        in: formData
        name: queryWord
        required: true
        type: string
      responses: {}
  /login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":202,"success":false,"msg":"password doesn''t match"}'
          schema:
            type: string
      summary: ccf
      tags:
      - 用户
  /register:
    post:
      consumes:
      - application/json
      description: 填入用户名和密码注册
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.RegisterQ'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":201,"msg":"username exists"}'
          schema:
            type: string
      summary: ccf
      tags:
      - 用户
  /userinfo:
    post:
      consumes:
      - application/json
      description: 查看用户个人信息
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"success":false,"msg":"userID not exist"}'
          schema:
            type: string
      summary: ccf
      tags:
      - 用户
  /usermod:
    post:
      consumes:
      - application/json
      description: 编辑用户信息
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      - description: 个性签名
        in: query
        name: user_info
        required: true
        type: string
      - description: 电话号码
        in: query
        name: phone_number
        required: true
        type: string
      - description: Email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"success":false,"msg":err.Error()}'
          schema:
            type: string
      summary: ccf
      tags:
      - 用户
swagger: "2.0"
