# deploy gin to server
name: deploy gin to server
on:
  #监听push操作
  push:
    branches:
      - main
      - dev
jobs:
  # 任务ID
  deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
    # 使用别人的action
    - uses: actions/checkout@v2
    # 步骤名称
    # 命名这个任务为发布Deploy
    - name: build
      # 运行命令
      run: |
        # 打包
        go build -o IShare
    - name: Deploy to HUAWEIYUN Server
      uses: